### ISSUE TITLE
[Enhance]Using OsTag variables in Tips.

### ISSUE THREAD

**Issue by Dbackolds** [IndianBartonka/OsTag#3]
I suggest adding some variables to the OsTag plugin in Tips (https://cloudburstmc.org/resources/tips.863/) so that users of Tips don't conflict with OsTag. I'm really looking forward to having such an update with OsTag variables in Tips. You can download the latest version of Tips at https://ci.lanink.cn/job/Tips/. I'm truly excited about the prospect of this update.

Of course, you can interpret it this way: using OsTag variables in Tips.

**Comment by IndianBartonka** [comment]
What you mean?

**Comment by IndianBartonka** [comment]
> I suggest adding some variables to the OsTag plugin in Tips (https://cloudburstmc.org/resources/tips.863/) so that users of Tips don't conflict with OsTag. I'm really looking forward to having such an update with OsTag variables in Tips. You can download the latest version of Tips at https://ci.lanink.cn/job/Tips/. I'm truly excited about the prospect of this update.
> 
> Of course, you can interpret it this way: using OsTag variables in Tips.

What is in conflict?

**Comment by Dbackolds** [comment]
> > I suggest adding some variables to the OsTag plugin in Tips (https://cloudburstmc.org/resources/tips.863/) so that users of Tips don't conflict with OsTag. I'm really looking forward to having such an update with OsTag variables in Tips. You can download the latest version of Tips at https://ci.lanink.cn/job/Tips/. I'm truly excited about the prospect of this update.
> > Of course, you can interpret it this way: using OsTag variables in Tips.
> 
> What is in conflict?

The two plugins can't be used together.

I wish I could make the variables from OsTag usable in Tips.
